// Code generated by ent, DO NOT EDIT.

package upstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPlatform, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPassword, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRefreshToken, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldExpiresAt, v))
}

// SessionCookie applies equality check predicate on the "session_cookie" field. It's identical to SessionCookieEQ.
func SessionCookie(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldSessionCookie, v))
}

// UpstreamUserID applies equality check predicate on the "upstream_user_id" field. It's identical to UpstreamUserIDEQ.
func UpstreamUserID(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpstreamUserID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBalance, v))
}

// Health applies equality check predicate on the "health" field. It's identical to HealthEQ.
func Health(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldHealth, v))
}

// HealthMsg applies equality check predicate on the "health_msg" field. It's identical to HealthMsgEQ.
func HealthMsg(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldHealthMsg, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldPlatform, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldBaseURL, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldPassword, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldRefreshToken, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldExpiresAt))
}

// SessionCookieEQ applies the EQ predicate on the "session_cookie" field.
func SessionCookieEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldSessionCookie, v))
}

// SessionCookieNEQ applies the NEQ predicate on the "session_cookie" field.
func SessionCookieNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldSessionCookie, v))
}

// SessionCookieIn applies the In predicate on the "session_cookie" field.
func SessionCookieIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldSessionCookie, vs...))
}

// SessionCookieNotIn applies the NotIn predicate on the "session_cookie" field.
func SessionCookieNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldSessionCookie, vs...))
}

// SessionCookieGT applies the GT predicate on the "session_cookie" field.
func SessionCookieGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldSessionCookie, v))
}

// SessionCookieGTE applies the GTE predicate on the "session_cookie" field.
func SessionCookieGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldSessionCookie, v))
}

// SessionCookieLT applies the LT predicate on the "session_cookie" field.
func SessionCookieLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldSessionCookie, v))
}

// SessionCookieLTE applies the LTE predicate on the "session_cookie" field.
func SessionCookieLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldSessionCookie, v))
}

// SessionCookieContains applies the Contains predicate on the "session_cookie" field.
func SessionCookieContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldSessionCookie, v))
}

// SessionCookieHasPrefix applies the HasPrefix predicate on the "session_cookie" field.
func SessionCookieHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldSessionCookie, v))
}

// SessionCookieHasSuffix applies the HasSuffix predicate on the "session_cookie" field.
func SessionCookieHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldSessionCookie, v))
}

// SessionCookieIsNil applies the IsNil predicate on the "session_cookie" field.
func SessionCookieIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldSessionCookie))
}

// SessionCookieNotNil applies the NotNil predicate on the "session_cookie" field.
func SessionCookieNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldSessionCookie))
}

// SessionCookieEqualFold applies the EqualFold predicate on the "session_cookie" field.
func SessionCookieEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldSessionCookie, v))
}

// SessionCookieContainsFold applies the ContainsFold predicate on the "session_cookie" field.
func SessionCookieContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldSessionCookie, v))
}

// UpstreamUserIDEQ applies the EQ predicate on the "upstream_user_id" field.
func UpstreamUserIDEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpstreamUserID, v))
}

// UpstreamUserIDNEQ applies the NEQ predicate on the "upstream_user_id" field.
func UpstreamUserIDNEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldUpstreamUserID, v))
}

// UpstreamUserIDIn applies the In predicate on the "upstream_user_id" field.
func UpstreamUserIDIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldUpstreamUserID, vs...))
}

// UpstreamUserIDNotIn applies the NotIn predicate on the "upstream_user_id" field.
func UpstreamUserIDNotIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldUpstreamUserID, vs...))
}

// UpstreamUserIDGT applies the GT predicate on the "upstream_user_id" field.
func UpstreamUserIDGT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldUpstreamUserID, v))
}

// UpstreamUserIDGTE applies the GTE predicate on the "upstream_user_id" field.
func UpstreamUserIDGTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldUpstreamUserID, v))
}

// UpstreamUserIDLT applies the LT predicate on the "upstream_user_id" field.
func UpstreamUserIDLT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldUpstreamUserID, v))
}

// UpstreamUserIDLTE applies the LTE predicate on the "upstream_user_id" field.
func UpstreamUserIDLTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldUpstreamUserID, v))
}

// UpstreamUserIDIsNil applies the IsNil predicate on the "upstream_user_id" field.
func UpstreamUserIDIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldUpstreamUserID))
}

// UpstreamUserIDNotNil applies the NotNil predicate on the "upstream_user_id" field.
func UpstreamUserIDNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldUpstreamUserID))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldBalance, v))
}

// HealthEQ applies the EQ predicate on the "health" field.
func HealthEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldHealth, v))
}

// HealthNEQ applies the NEQ predicate on the "health" field.
func HealthNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldHealth, v))
}

// HealthIn applies the In predicate on the "health" field.
func HealthIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldHealth, vs...))
}

// HealthNotIn applies the NotIn predicate on the "health" field.
func HealthNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldHealth, vs...))
}

// HealthGT applies the GT predicate on the "health" field.
func HealthGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldHealth, v))
}

// HealthGTE applies the GTE predicate on the "health" field.
func HealthGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldHealth, v))
}

// HealthLT applies the LT predicate on the "health" field.
func HealthLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldHealth, v))
}

// HealthLTE applies the LTE predicate on the "health" field.
func HealthLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldHealth, v))
}

// HealthContains applies the Contains predicate on the "health" field.
func HealthContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldHealth, v))
}

// HealthHasPrefix applies the HasPrefix predicate on the "health" field.
func HealthHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldHealth, v))
}

// HealthHasSuffix applies the HasSuffix predicate on the "health" field.
func HealthHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldHealth, v))
}

// HealthEqualFold applies the EqualFold predicate on the "health" field.
func HealthEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldHealth, v))
}

// HealthContainsFold applies the ContainsFold predicate on the "health" field.
func HealthContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldHealth, v))
}

// HealthMsgEQ applies the EQ predicate on the "health_msg" field.
func HealthMsgEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldHealthMsg, v))
}

// HealthMsgNEQ applies the NEQ predicate on the "health_msg" field.
func HealthMsgNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldHealthMsg, v))
}

// HealthMsgIn applies the In predicate on the "health_msg" field.
func HealthMsgIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldHealthMsg, vs...))
}

// HealthMsgNotIn applies the NotIn predicate on the "health_msg" field.
func HealthMsgNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldHealthMsg, vs...))
}

// HealthMsgGT applies the GT predicate on the "health_msg" field.
func HealthMsgGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldHealthMsg, v))
}

// HealthMsgGTE applies the GTE predicate on the "health_msg" field.
func HealthMsgGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldHealthMsg, v))
}

// HealthMsgLT applies the LT predicate on the "health_msg" field.
func HealthMsgLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldHealthMsg, v))
}

// HealthMsgLTE applies the LTE predicate on the "health_msg" field.
func HealthMsgLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldHealthMsg, v))
}

// HealthMsgContains applies the Contains predicate on the "health_msg" field.
func HealthMsgContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldHealthMsg, v))
}

// HealthMsgHasPrefix applies the HasPrefix predicate on the "health_msg" field.
func HealthMsgHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldHealthMsg, v))
}

// HealthMsgHasSuffix applies the HasSuffix predicate on the "health_msg" field.
func HealthMsgHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldHealthMsg, v))
}

// HealthMsgIsNil applies the IsNil predicate on the "health_msg" field.
func HealthMsgIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldHealthMsg))
}

// HealthMsgNotNil applies the NotNil predicate on the "health_msg" field.
func HealthMsgNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldHealthMsg))
}

// HealthMsgEqualFold applies the EqualFold predicate on the "health_msg" field.
func HealthMsgEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldHealthMsg, v))
}

// HealthMsgContainsFold applies the ContainsFold predicate on the "health_msg" field.
func HealthMsgContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldHealthMsg, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLastSyncedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.NotPredicates(p))
}
