// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// UpstreamUpdate is the builder for updating Upstream entities.
type UpstreamUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamMutation
}

// Where appends a list predicates to the UpstreamUpdate builder.
func (_u *UpstreamUpdate) Where(ps ...predicate.Upstream) *UpstreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUpdate) SetUpdatedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamUpdate) SetDeletedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamUpdate) ClearDeletedAt() *UpstreamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamUpdate) SetName(v string) *UpstreamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableName(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamUpdate) SetPlatform(v string) *UpstreamUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillablePlatform(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamUpdate) SetBaseURL(v string) *UpstreamUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableBaseURL(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UpstreamUpdate) SetEmail(v string) *UpstreamUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableEmail(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UpstreamUpdate) SetPassword(v string) *UpstreamUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillablePassword(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UpstreamUpdate) SetAccessToken(v string) *UpstreamUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableAccessToken(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UpstreamUpdate) ClearAccessToken() *UpstreamUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UpstreamUpdate) SetRefreshToken(v string) *UpstreamUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableRefreshToken(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UpstreamUpdate) ClearRefreshToken() *UpstreamUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UpstreamUpdate) SetExpiresAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableExpiresAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UpstreamUpdate) ClearExpiresAt() *UpstreamUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSessionCookie sets the "session_cookie" field.
func (_u *UpstreamUpdate) SetSessionCookie(v string) *UpstreamUpdate {
	_u.mutation.SetSessionCookie(v)
	return _u
}

// SetNillableSessionCookie sets the "session_cookie" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableSessionCookie(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetSessionCookie(*v)
	}
	return _u
}

// ClearSessionCookie clears the value of the "session_cookie" field.
func (_u *UpstreamUpdate) ClearSessionCookie() *UpstreamUpdate {
	_u.mutation.ClearSessionCookie()
	return _u
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (_u *UpstreamUpdate) SetUpstreamUserID(v int64) *UpstreamUpdate {
	_u.mutation.ResetUpstreamUserID()
	_u.mutation.SetUpstreamUserID(v)
	return _u
}

// SetNillableUpstreamUserID sets the "upstream_user_id" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableUpstreamUserID(v *int64) *UpstreamUpdate {
	if v != nil {
		_u.SetUpstreamUserID(*v)
	}
	return _u
}

// AddUpstreamUserID adds value to the "upstream_user_id" field.
func (_u *UpstreamUpdate) AddUpstreamUserID(v int64) *UpstreamUpdate {
	_u.mutation.AddUpstreamUserID(v)
	return _u
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (_u *UpstreamUpdate) ClearUpstreamUserID() *UpstreamUpdate {
	_u.mutation.ClearUpstreamUserID()
	return _u
}

// SetGroups sets the "groups" field.
func (_u *UpstreamUpdate) SetGroups(v []map[string]interface{}) *UpstreamUpdate {
	_u.mutation.SetGroups(v)
	return _u
}

// AppendGroups appends value to the "groups" field.
func (_u *UpstreamUpdate) AppendGroups(v []map[string]interface{}) *UpstreamUpdate {
	_u.mutation.AppendGroups(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamUpdate) SetBalance(v float64) *UpstreamUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableBalance(v *float64) *UpstreamUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamUpdate) AddBalance(v float64) *UpstreamUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetHealth sets the "health" field.
func (_u *UpstreamUpdate) SetHealth(v string) *UpstreamUpdate {
	_u.mutation.SetHealth(v)
	return _u
}

// SetNillableHealth sets the "health" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableHealth(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetHealth(*v)
	}
	return _u
}

// SetHealthMsg sets the "health_msg" field.
func (_u *UpstreamUpdate) SetHealthMsg(v string) *UpstreamUpdate {
	_u.mutation.SetHealthMsg(v)
	return _u
}

// SetNillableHealthMsg sets the "health_msg" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableHealthMsg(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetHealthMsg(*v)
	}
	return _u
}

// ClearHealthMsg clears the value of the "health_msg" field.
func (_u *UpstreamUpdate) ClearHealthMsg() *UpstreamUpdate {
	_u.mutation.ClearHealthMsg()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamUpdate) SetLastSyncedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableLastSyncedAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *UpstreamUpdate) ClearLastSyncedAt() *UpstreamUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// Mutation returns the UpstreamMutation object of the builder.
func (_u *UpstreamUpdate) Mutation() *UpstreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstream.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Upstream.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := upstream.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Upstream.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := upstream.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Upstream.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Health(); ok {
		if err := upstream.HealthValidator(v); err != nil {
			return &ValidationError{Name: "health", err: fmt.Errorf(`ent: validator failed for field "Upstream.health": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstream.Table, upstream.Columns, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstream.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(upstream.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(upstream.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(upstream.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(upstream.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(upstream.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(upstream.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(upstream.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(upstream.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionCookie(); ok {
		_spec.SetField(upstream.FieldSessionCookie, field.TypeString, value)
	}
	if _u.mutation.SessionCookieCleared() {
		_spec.ClearField(upstream.FieldSessionCookie, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamUserID(); ok {
		_spec.SetField(upstream.FieldUpstreamUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUserID(); ok {
		_spec.AddField(upstream.FieldUpstreamUserID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamUserIDCleared() {
		_spec.ClearField(upstream.FieldUpstreamUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Groups(); ok {
		_spec.SetField(upstream.FieldGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstream.FieldGroups, value)
		})
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstream.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstream.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Health(); ok {
		_spec.SetField(upstream.FieldHealth, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthMsg(); ok {
		_spec.SetField(upstream.FieldHealthMsg, field.TypeString, value)
	}
	if _u.mutation.HealthMsgCleared() {
		_spec.ClearField(upstream.FieldHealthMsg, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstream.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(upstream.FieldLastSyncedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamUpdateOne is the builder for updating a single Upstream entity.
type UpstreamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUpdateOne) SetUpdatedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamUpdateOne) SetDeletedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamUpdateOne) ClearDeletedAt() *UpstreamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamUpdateOne) SetName(v string) *UpstreamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableName(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamUpdateOne) SetPlatform(v string) *UpstreamUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillablePlatform(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamUpdateOne) SetBaseURL(v string) *UpstreamUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableBaseURL(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UpstreamUpdateOne) SetEmail(v string) *UpstreamUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableEmail(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UpstreamUpdateOne) SetPassword(v string) *UpstreamUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillablePassword(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UpstreamUpdateOne) SetAccessToken(v string) *UpstreamUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableAccessToken(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UpstreamUpdateOne) ClearAccessToken() *UpstreamUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UpstreamUpdateOne) SetRefreshToken(v string) *UpstreamUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableRefreshToken(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UpstreamUpdateOne) ClearRefreshToken() *UpstreamUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UpstreamUpdateOne) SetExpiresAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableExpiresAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UpstreamUpdateOne) ClearExpiresAt() *UpstreamUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSessionCookie sets the "session_cookie" field.
func (_u *UpstreamUpdateOne) SetSessionCookie(v string) *UpstreamUpdateOne {
	_u.mutation.SetSessionCookie(v)
	return _u
}

// SetNillableSessionCookie sets the "session_cookie" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableSessionCookie(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetSessionCookie(*v)
	}
	return _u
}

// ClearSessionCookie clears the value of the "session_cookie" field.
func (_u *UpstreamUpdateOne) ClearSessionCookie() *UpstreamUpdateOne {
	_u.mutation.ClearSessionCookie()
	return _u
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (_u *UpstreamUpdateOne) SetUpstreamUserID(v int64) *UpstreamUpdateOne {
	_u.mutation.ResetUpstreamUserID()
	_u.mutation.SetUpstreamUserID(v)
	return _u
}

// SetNillableUpstreamUserID sets the "upstream_user_id" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableUpstreamUserID(v *int64) *UpstreamUpdateOne {
	if v != nil {
		_u.SetUpstreamUserID(*v)
	}
	return _u
}

// AddUpstreamUserID adds value to the "upstream_user_id" field.
func (_u *UpstreamUpdateOne) AddUpstreamUserID(v int64) *UpstreamUpdateOne {
	_u.mutation.AddUpstreamUserID(v)
	return _u
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (_u *UpstreamUpdateOne) ClearUpstreamUserID() *UpstreamUpdateOne {
	_u.mutation.ClearUpstreamUserID()
	return _u
}

// SetGroups sets the "groups" field.
func (_u *UpstreamUpdateOne) SetGroups(v []map[string]interface{}) *UpstreamUpdateOne {
	_u.mutation.SetGroups(v)
	return _u
}

// AppendGroups appends value to the "groups" field.
func (_u *UpstreamUpdateOne) AppendGroups(v []map[string]interface{}) *UpstreamUpdateOne {
	_u.mutation.AppendGroups(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamUpdateOne) SetBalance(v float64) *UpstreamUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableBalance(v *float64) *UpstreamUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamUpdateOne) AddBalance(v float64) *UpstreamUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetHealth sets the "health" field.
func (_u *UpstreamUpdateOne) SetHealth(v string) *UpstreamUpdateOne {
	_u.mutation.SetHealth(v)
	return _u
}

// SetNillableHealth sets the "health" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableHealth(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetHealth(*v)
	}
	return _u
}

// SetHealthMsg sets the "health_msg" field.
func (_u *UpstreamUpdateOne) SetHealthMsg(v string) *UpstreamUpdateOne {
	_u.mutation.SetHealthMsg(v)
	return _u
}

// SetNillableHealthMsg sets the "health_msg" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableHealthMsg(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetHealthMsg(*v)
	}
	return _u
}

// ClearHealthMsg clears the value of the "health_msg" field.
func (_u *UpstreamUpdateOne) ClearHealthMsg() *UpstreamUpdateOne {
	_u.mutation.ClearHealthMsg()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamUpdateOne) SetLastSyncedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableLastSyncedAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *UpstreamUpdateOne) ClearLastSyncedAt() *UpstreamUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// Mutation returns the UpstreamMutation object of the builder.
func (_u *UpstreamUpdateOne) Mutation() *UpstreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamUpdate builder.
func (_u *UpstreamUpdateOne) Where(ps ...predicate.Upstream) *UpstreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamUpdateOne) Select(field string, fields ...string) *UpstreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Upstream entity.
func (_u *UpstreamUpdateOne) Save(ctx context.Context) (*Upstream, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUpdateOne) SaveX(ctx context.Context) *Upstream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstream.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Upstream.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := upstream.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Upstream.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := upstream.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Upstream.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Health(); ok {
		if err := upstream.HealthValidator(v); err != nil {
			return &ValidationError{Name: "health", err: fmt.Errorf(`ent: validator failed for field "Upstream.health": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUpdateOne) sqlSave(ctx context.Context) (_node *Upstream, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstream.Table, upstream.Columns, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upstream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstream.FieldID)
		for _, f := range fields {
			if !upstream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstream.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(upstream.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(upstream.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(upstream.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(upstream.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(upstream.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(upstream.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(upstream.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(upstream.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SessionCookie(); ok {
		_spec.SetField(upstream.FieldSessionCookie, field.TypeString, value)
	}
	if _u.mutation.SessionCookieCleared() {
		_spec.ClearField(upstream.FieldSessionCookie, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamUserID(); ok {
		_spec.SetField(upstream.FieldUpstreamUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamUserID(); ok {
		_spec.AddField(upstream.FieldUpstreamUserID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamUserIDCleared() {
		_spec.ClearField(upstream.FieldUpstreamUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Groups(); ok {
		_spec.SetField(upstream.FieldGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstream.FieldGroups, value)
		})
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstream.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstream.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Health(); ok {
		_spec.SetField(upstream.FieldHealth, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthMsg(); ok {
		_spec.SetField(upstream.FieldHealthMsg, field.TypeString, value)
	}
	if _u.mutation.HealthMsgCleared() {
		_spec.ClearField(upstream.FieldHealthMsg, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstream.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(upstream.FieldLastSyncedAt, field.TypeTime)
	}
	_node = &Upstream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
