// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// UpstreamCreate is the builder for creating a Upstream entity.
type UpstreamCreate struct {
	config
	mutation *UpstreamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamCreate) SetCreatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableCreatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamCreate) SetUpdatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamCreate) SetDeletedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableDeletedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamCreate) SetName(v string) *UpstreamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UpstreamCreate) SetPlatform(v string) *UpstreamCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamCreate) SetBaseURL(v string) *UpstreamCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UpstreamCreate) SetEmail(v string) *UpstreamCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *UpstreamCreate) SetPassword(v string) *UpstreamCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *UpstreamCreate) SetAccessToken(v string) *UpstreamCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableAccessToken(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *UpstreamCreate) SetRefreshToken(v string) *UpstreamCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableRefreshToken(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UpstreamCreate) SetExpiresAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableExpiresAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetSessionCookie sets the "session_cookie" field.
func (_c *UpstreamCreate) SetSessionCookie(v string) *UpstreamCreate {
	_c.mutation.SetSessionCookie(v)
	return _c
}

// SetNillableSessionCookie sets the "session_cookie" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableSessionCookie(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetSessionCookie(*v)
	}
	return _c
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (_c *UpstreamCreate) SetUpstreamUserID(v int64) *UpstreamCreate {
	_c.mutation.SetUpstreamUserID(v)
	return _c
}

// SetNillableUpstreamUserID sets the "upstream_user_id" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableUpstreamUserID(v *int64) *UpstreamCreate {
	if v != nil {
		_c.SetUpstreamUserID(*v)
	}
	return _c
}

// SetGroups sets the "groups" field.
func (_c *UpstreamCreate) SetGroups(v []map[string]interface{}) *UpstreamCreate {
	_c.mutation.SetGroups(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *UpstreamCreate) SetBalance(v float64) *UpstreamCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableBalance(v *float64) *UpstreamCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetHealth sets the "health" field.
func (_c *UpstreamCreate) SetHealth(v string) *UpstreamCreate {
	_c.mutation.SetHealth(v)
	return _c
}

// SetNillableHealth sets the "health" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableHealth(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetHealth(*v)
	}
	return _c
}

// SetHealthMsg sets the "health_msg" field.
func (_c *UpstreamCreate) SetHealthMsg(v string) *UpstreamCreate {
	_c.mutation.SetHealthMsg(v)
	return _c
}

// SetNillableHealthMsg sets the "health_msg" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableHealthMsg(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetHealthMsg(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *UpstreamCreate) SetLastSyncedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLastSyncedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// Mutation returns the UpstreamMutation object of the builder.
func (_c *UpstreamCreate) Mutation() *UpstreamMutation {
	return _c.mutation
}

// Save creates the Upstream in the database.
func (_c *UpstreamCreate) Save(ctx context.Context) (*Upstream, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamCreate) SaveX(ctx context.Context) *Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstream.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstream.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Groups(); !ok {
		v := upstream.DefaultGroups
		_c.mutation.SetGroups(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := upstream.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.Health(); !ok {
		v := upstream.DefaultHealth
		_c.mutation.SetHealth(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Upstream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Upstream.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Upstream.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Upstream.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := upstream.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Upstream.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "Upstream.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Upstream.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := upstream.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Upstream.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Upstream.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := upstream.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Upstream.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Groups(); !ok {
		return &ValidationError{Name: "groups", err: errors.New(`ent: missing required field "Upstream.groups"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Upstream.balance"`)}
	}
	if _, ok := _c.mutation.Health(); !ok {
		return &ValidationError{Name: "health", err: errors.New(`ent: missing required field "Upstream.health"`)}
	}
	if v, ok := _c.mutation.Health(); ok {
		if err := upstream.HealthValidator(v); err != nil {
			return &ValidationError{Name: "health", err: fmt.Errorf(`ent: validator failed for field "Upstream.health": %w`, err)}
		}
	}
	return nil
}

func (_c *UpstreamCreate) sqlSave(ctx context.Context) (*Upstream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamCreate) createSpec() (*Upstream, *sqlgraph.CreateSpec) {
	var (
		_node = &Upstream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstream.Table, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(upstream.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(upstream.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(upstream.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(upstream.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = &value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(upstream.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(upstream.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.SessionCookie(); ok {
		_spec.SetField(upstream.FieldSessionCookie, field.TypeString, value)
		_node.SessionCookie = &value
	}
	if value, ok := _c.mutation.UpstreamUserID(); ok {
		_spec.SetField(upstream.FieldUpstreamUserID, field.TypeInt64, value)
		_node.UpstreamUserID = &value
	}
	if value, ok := _c.mutation.Groups(); ok {
		_spec.SetField(upstream.FieldGroups, field.TypeJSON, value)
		_node.Groups = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(upstream.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.Health(); ok {
		_spec.SetField(upstream.FieldHealth, field.TypeString, value)
		_node.Health = value
	}
	if value, ok := _c.mutation.HealthMsg(); ok {
		_spec.SetField(upstream.FieldHealthMsg, field.TypeString, value)
		_node.HealthMsg = &value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstream.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertOne {
	_c.conflict = opts
	return &UpstreamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflictColumns(columns ...string) *UpstreamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamUpsertOne is the builder for "upsert"-ing
	//  one Upstream node.
	UpstreamUpsertOne struct {
		create *UpstreamCreate
	}

	// UpstreamUpsert is the "OnConflict" setter.
	UpstreamUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsert) SetUpdatedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateUpdatedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsert) SetDeletedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateDeletedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsert) ClearDeletedAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamUpsert) SetName(v string) *UpstreamUpsert {
	u.Set(upstream.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateName() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *UpstreamUpsert) SetPlatform(v string) *UpstreamUpsert {
	u.Set(upstream.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdatePlatform() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldPlatform)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsert) SetBaseURL(v string) *UpstreamUpsert {
	u.Set(upstream.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateBaseURL() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldBaseURL)
	return u
}

// SetEmail sets the "email" field.
func (u *UpstreamUpsert) SetEmail(v string) *UpstreamUpsert {
	u.Set(upstream.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateEmail() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldEmail)
	return u
}

// SetPassword sets the "password" field.
func (u *UpstreamUpsert) SetPassword(v string) *UpstreamUpsert {
	u.Set(upstream.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdatePassword() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldPassword)
	return u
}

// SetAccessToken sets the "access_token" field.
func (u *UpstreamUpsert) SetAccessToken(v string) *UpstreamUpsert {
	u.Set(upstream.FieldAccessToken, v)
	return u
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateAccessToken() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldAccessToken)
	return u
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *UpstreamUpsert) ClearAccessToken() *UpstreamUpsert {
	u.SetNull(upstream.FieldAccessToken)
	return u
}

// SetRefreshToken sets the "refresh_token" field.
func (u *UpstreamUpsert) SetRefreshToken(v string) *UpstreamUpsert {
	u.Set(upstream.FieldRefreshToken, v)
	return u
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateRefreshToken() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldRefreshToken)
	return u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *UpstreamUpsert) ClearRefreshToken() *UpstreamUpsert {
	u.SetNull(upstream.FieldRefreshToken)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UpstreamUpsert) SetExpiresAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateExpiresAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UpstreamUpsert) ClearExpiresAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldExpiresAt)
	return u
}

// SetSessionCookie sets the "session_cookie" field.
func (u *UpstreamUpsert) SetSessionCookie(v string) *UpstreamUpsert {
	u.Set(upstream.FieldSessionCookie, v)
	return u
}

// UpdateSessionCookie sets the "session_cookie" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateSessionCookie() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldSessionCookie)
	return u
}

// ClearSessionCookie clears the value of the "session_cookie" field.
func (u *UpstreamUpsert) ClearSessionCookie() *UpstreamUpsert {
	u.SetNull(upstream.FieldSessionCookie)
	return u
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (u *UpstreamUpsert) SetUpstreamUserID(v int64) *UpstreamUpsert {
	u.Set(upstream.FieldUpstreamUserID, v)
	return u
}

// UpdateUpstreamUserID sets the "upstream_user_id" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateUpstreamUserID() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldUpstreamUserID)
	return u
}

// AddUpstreamUserID adds v to the "upstream_user_id" field.
func (u *UpstreamUpsert) AddUpstreamUserID(v int64) *UpstreamUpsert {
	u.Add(upstream.FieldUpstreamUserID, v)
	return u
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (u *UpstreamUpsert) ClearUpstreamUserID() *UpstreamUpsert {
	u.SetNull(upstream.FieldUpstreamUserID)
	return u
}

// SetGroups sets the "groups" field.
func (u *UpstreamUpsert) SetGroups(v []map[string]interface{}) *UpstreamUpsert {
	u.Set(upstream.FieldGroups, v)
	return u
}

// UpdateGroups sets the "groups" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateGroups() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldGroups)
	return u
}

// SetBalance sets the "balance" field.
func (u *UpstreamUpsert) SetBalance(v float64) *UpstreamUpsert {
	u.Set(upstream.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateBalance() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamUpsert) AddBalance(v float64) *UpstreamUpsert {
	u.Add(upstream.FieldBalance, v)
	return u
}

// SetHealth sets the "health" field.
func (u *UpstreamUpsert) SetHealth(v string) *UpstreamUpsert {
	u.Set(upstream.FieldHealth, v)
	return u
}

// UpdateHealth sets the "health" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateHealth() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldHealth)
	return u
}

// SetHealthMsg sets the "health_msg" field.
func (u *UpstreamUpsert) SetHealthMsg(v string) *UpstreamUpsert {
	u.Set(upstream.FieldHealthMsg, v)
	return u
}

// UpdateHealthMsg sets the "health_msg" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateHealthMsg() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldHealthMsg)
	return u
}

// ClearHealthMsg clears the value of the "health_msg" field.
func (u *UpstreamUpsert) ClearHealthMsg() *UpstreamUpsert {
	u.SetNull(upstream.FieldHealthMsg)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamUpsert) SetLastSyncedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLastSyncedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamUpsert) ClearLastSyncedAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldLastSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertOne) UpdateNewValues() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstream.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamUpsertOne) Ignore() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertOne) DoNothing() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreate.OnConflict
// documentation for more info.
func (u *UpstreamUpsertOne) Update(set func(*UpstreamUpsert)) *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertOne) SetUpdatedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateUpdatedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertOne) SetDeletedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertOne) ClearDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertOne) SetName(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateName() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamUpsertOne) SetPlatform(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdatePlatform() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePlatform()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertOne) SetBaseURL(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateBaseURL() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEmail sets the "email" field.
func (u *UpstreamUpsertOne) SetEmail(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateEmail() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *UpstreamUpsertOne) SetPassword(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdatePassword() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePassword()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *UpstreamUpsertOne) SetAccessToken(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateAccessToken() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateAccessToken()
	})
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *UpstreamUpsertOne) ClearAccessToken() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearAccessToken()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *UpstreamUpsertOne) SetRefreshToken(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateRefreshToken() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRefreshToken()
	})
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *UpstreamUpsertOne) ClearRefreshToken() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRefreshToken()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UpstreamUpsertOne) SetExpiresAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateExpiresAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UpstreamUpsertOne) ClearExpiresAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSessionCookie sets the "session_cookie" field.
func (u *UpstreamUpsertOne) SetSessionCookie(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetSessionCookie(v)
	})
}

// UpdateSessionCookie sets the "session_cookie" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateSessionCookie() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateSessionCookie()
	})
}

// ClearSessionCookie clears the value of the "session_cookie" field.
func (u *UpstreamUpsertOne) ClearSessionCookie() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearSessionCookie()
	})
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (u *UpstreamUpsertOne) SetUpstreamUserID(v int64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpstreamUserID(v)
	})
}

// AddUpstreamUserID adds v to the "upstream_user_id" field.
func (u *UpstreamUpsertOne) AddUpstreamUserID(v int64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddUpstreamUserID(v)
	})
}

// UpdateUpstreamUserID sets the "upstream_user_id" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateUpstreamUserID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpstreamUserID()
	})
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (u *UpstreamUpsertOne) ClearUpstreamUserID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearUpstreamUserID()
	})
}

// SetGroups sets the "groups" field.
func (u *UpstreamUpsertOne) SetGroups(v []map[string]interface{}) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetGroups(v)
	})
}

// UpdateGroups sets the "groups" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateGroups() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateGroups()
	})
}

// SetBalance sets the "balance" field.
func (u *UpstreamUpsertOne) SetBalance(v float64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamUpsertOne) AddBalance(v float64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateBalance() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBalance()
	})
}

// SetHealth sets the "health" field.
func (u *UpstreamUpsertOne) SetHealth(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetHealth(v)
	})
}

// UpdateHealth sets the "health" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateHealth() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateHealth()
	})
}

// SetHealthMsg sets the "health_msg" field.
func (u *UpstreamUpsertOne) SetHealthMsg(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetHealthMsg(v)
	})
}

// UpdateHealthMsg sets the "health_msg" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateHealthMsg() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateHealthMsg()
	})
}

// ClearHealthMsg clears the value of the "health_msg" field.
func (u *UpstreamUpsertOne) ClearHealthMsg() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearHealthMsg()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamUpsertOne) SetLastSyncedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLastSyncedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamUpsertOne) ClearLastSyncedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamCreateBulk is the builder for creating many Upstream entities in bulk.
type UpstreamCreateBulk struct {
	config
	err      error
	builders []*UpstreamCreate
	conflict []sql.ConflictOption
}

// Save creates the Upstream entities in the database.
func (_c *UpstreamCreateBulk) Save(ctx context.Context) ([]*Upstream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Upstream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamCreateBulk) SaveX(ctx context.Context) []*Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertBulk {
	_c.conflict = opts
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflictColumns(columns ...string) *UpstreamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// UpstreamUpsertBulk is the builder for "upsert"-ing
// a bulk of Upstream nodes.
type UpstreamUpsertBulk struct {
	create *UpstreamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) UpdateNewValues() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstream.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) Ignore() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertBulk) DoNothing() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamUpsertBulk) Update(set func(*UpstreamUpsert)) *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateUpdatedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertBulk) SetDeletedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertBulk) ClearDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertBulk) SetName(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateName() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamUpsertBulk) SetPlatform(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdatePlatform() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePlatform()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertBulk) SetBaseURL(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateBaseURL() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEmail sets the "email" field.
func (u *UpstreamUpsertBulk) SetEmail(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateEmail() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *UpstreamUpsertBulk) SetPassword(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdatePassword() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePassword()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *UpstreamUpsertBulk) SetAccessToken(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateAccessToken() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateAccessToken()
	})
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *UpstreamUpsertBulk) ClearAccessToken() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearAccessToken()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *UpstreamUpsertBulk) SetRefreshToken(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateRefreshToken() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRefreshToken()
	})
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *UpstreamUpsertBulk) ClearRefreshToken() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRefreshToken()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UpstreamUpsertBulk) SetExpiresAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateExpiresAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UpstreamUpsertBulk) ClearExpiresAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSessionCookie sets the "session_cookie" field.
func (u *UpstreamUpsertBulk) SetSessionCookie(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetSessionCookie(v)
	})
}

// UpdateSessionCookie sets the "session_cookie" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateSessionCookie() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateSessionCookie()
	})
}

// ClearSessionCookie clears the value of the "session_cookie" field.
func (u *UpstreamUpsertBulk) ClearSessionCookie() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearSessionCookie()
	})
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (u *UpstreamUpsertBulk) SetUpstreamUserID(v int64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpstreamUserID(v)
	})
}

// AddUpstreamUserID adds v to the "upstream_user_id" field.
func (u *UpstreamUpsertBulk) AddUpstreamUserID(v int64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddUpstreamUserID(v)
	})
}

// UpdateUpstreamUserID sets the "upstream_user_id" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateUpstreamUserID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpstreamUserID()
	})
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (u *UpstreamUpsertBulk) ClearUpstreamUserID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearUpstreamUserID()
	})
}

// SetGroups sets the "groups" field.
func (u *UpstreamUpsertBulk) SetGroups(v []map[string]interface{}) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetGroups(v)
	})
}

// UpdateGroups sets the "groups" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateGroups() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateGroups()
	})
}

// SetBalance sets the "balance" field.
func (u *UpstreamUpsertBulk) SetBalance(v float64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamUpsertBulk) AddBalance(v float64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateBalance() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBalance()
	})
}

// SetHealth sets the "health" field.
func (u *UpstreamUpsertBulk) SetHealth(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetHealth(v)
	})
}

// UpdateHealth sets the "health" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateHealth() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateHealth()
	})
}

// SetHealthMsg sets the "health_msg" field.
func (u *UpstreamUpsertBulk) SetHealthMsg(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetHealthMsg(v)
	})
}

// UpdateHealthMsg sets the "health_msg" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateHealthMsg() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateHealthMsg()
	})
}

// ClearHealthMsg clears the value of the "health_msg" field.
func (u *UpstreamUpsertBulk) ClearHealthMsg() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearHealthMsg()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamUpsertBulk) SetLastSyncedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLastSyncedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamUpsertBulk) ClearLastSyncedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
